version: "3"
services:
  ping:
    links:
      - pong
    environment:
      - PONG_ADDRESS=http://pong:8080/pong
  pong:
    environment:
      - PORT=8080
    # https://vscode-eastus.azurewebsites.net/docs/remote/containers-advanced#_connecting-to-multiple-containers-at-once
    # Trips: https://stackoverflow.com/questions/56267890/docker-compose-unable-to-start